// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: user/userService.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_QueryUserByUserId_FullMethodName    = "/user.UserService/QueryUserByUserId"
	UserService_QueryUserByUsername_FullMethodName  = "/user.UserService/QueryUserByUsername"
	UserService_QueryUserDeletionNum_FullMethodName = "/user.UserService/QueryUserDeletionNum"
	UserService_Update_FullMethodName               = "/user.UserService/Update"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户信息服务接口
type UserServiceClient interface {
	// 根据用户 ID 查询用户信息
	QueryUserByUserId(ctx context.Context, in *QueryUserByUserIdReq, opts ...grpc.CallOption) (*QueryUserResp, error)
	// 根据用户名查询用户信息
	QueryUserByUsername(ctx context.Context, in *QueryUserByUsernameReq, opts ...grpc.CallOption) (*QueryUserResp, error)
	// 根据证件类型和证件号查询注销次数
	QueryUserDeletionNum(ctx context.Context, in *QueryUserDeletionNumReq, opts ...grpc.CallOption) (*QueryUserDeletionNumResp, error)
	// 根据用户 ID 修改用户信息
	Update(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) QueryUserByUserId(ctx context.Context, in *QueryUserByUserIdReq, opts ...grpc.CallOption) (*QueryUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserResp)
	err := c.cc.Invoke(ctx, UserService_QueryUserByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) QueryUserByUsername(ctx context.Context, in *QueryUserByUsernameReq, opts ...grpc.CallOption) (*QueryUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserResp)
	err := c.cc.Invoke(ctx, UserService_QueryUserByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) QueryUserDeletionNum(ctx context.Context, in *QueryUserDeletionNumReq, opts ...grpc.CallOption) (*QueryUserDeletionNumResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserDeletionNumResp)
	err := c.cc.Invoke(ctx, UserService_QueryUserDeletionNum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUpdateResp)
	err := c.cc.Invoke(ctx, UserService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// 用户信息服务接口
type UserServiceServer interface {
	// 根据用户 ID 查询用户信息
	QueryUserByUserId(context.Context, *QueryUserByUserIdReq) (*QueryUserResp, error)
	// 根据用户名查询用户信息
	QueryUserByUsername(context.Context, *QueryUserByUsernameReq) (*QueryUserResp, error)
	// 根据证件类型和证件号查询注销次数
	QueryUserDeletionNum(context.Context, *QueryUserDeletionNumReq) (*QueryUserDeletionNumResp, error)
	// 根据用户 ID 修改用户信息
	Update(context.Context, *UserUpdateReq) (*UserUpdateResp, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) QueryUserByUserId(context.Context, *QueryUserByUserIdReq) (*QueryUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserByUserId not implemented")
}
func (UnimplementedUserServiceServer) QueryUserByUsername(context.Context, *QueryUserByUsernameReq) (*QueryUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserByUsername not implemented")
}
func (UnimplementedUserServiceServer) QueryUserDeletionNum(context.Context, *QueryUserDeletionNumReq) (*QueryUserDeletionNumResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserDeletionNum not implemented")
}
func (UnimplementedUserServiceServer) Update(context.Context, *UserUpdateReq) (*UserUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_QueryUserByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserByUserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QueryUserByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QueryUserByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QueryUserByUserId(ctx, req.(*QueryUserByUserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_QueryUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserByUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QueryUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QueryUserByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QueryUserByUsername(ctx, req.(*QueryUserByUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_QueryUserDeletionNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserDeletionNumReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QueryUserDeletionNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QueryUserDeletionNum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QueryUserDeletionNum(ctx, req.(*QueryUserDeletionNumReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UserUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryUserByUserId",
			Handler:    _UserService_QueryUserByUserId_Handler,
		},
		{
			MethodName: "QueryUserByUsername",
			Handler:    _UserService_QueryUserByUsername_Handler,
		},
		{
			MethodName: "QueryUserDeletionNum",
			Handler:    _UserService_QueryUserDeletionNum_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/userService.proto",
}
